import { GroupedTagsDto } from './tags.types';

export const TAGS: GroupedTagsDto = {
  genre: [
    { id: '1', name: 'Rock', type: 'genre' },
    { id: '2', name: 'Alternative Rock', type: 'genre' },
    { id: '3', name: 'Hard Rock', type: 'genre' },
    { id: '4', name: 'Progressive Rock', type: 'genre' },
    { id: '5', name: 'Pop', type: 'genre' },
    { id: '6', name: 'Synthpop', type: 'genre' },
    { id: '7', name: 'Electropop', type: 'genre' },
    { id: '8', name: 'Hip Hop', type: 'genre' },
    { id: '9', name: 'Trap', type: 'genre' },
    { id: '10', name: 'Boom Bap', type: 'genre' },
    { id: '11', name: 'Jazz', type: 'genre' },
    { id: '12', name: 'Smooth Jazz', type: 'genre' },
    { id: '13', name: 'Free Jazz', type: 'genre' },
    { id: '14', name: 'Classical', type: 'genre' },
    { id: '15', name: 'Baroque', type: 'genre' },
    { id: '16', name: 'Romantic', type: 'genre' },
    { id: '17', name: 'Electronic', type: 'genre' },
    { id: '18', name: 'Ambient', type: 'genre' },
    { id: '19', name: 'Downtempo', type: 'genre' },
    { id: '20', name: 'Reggae', type: 'genre' },
    { id: '21', name: 'Dancehall', type: 'genre' },
    { id: '22', name: 'Dub', type: 'genre' },
    { id: '23', name: 'Country', type: 'genre' },
    { id: '24', name: 'Bluegrass', type: 'genre' },
    { id: '25', name: 'Country Pop', type: 'genre' },
    { id: '26', name: 'Blues', type: 'genre' },
    { id: '27', name: 'Delta Blues', type: 'genre' },
    { id: '28', name: 'Chicago Blues', type: 'genre' },
    { id: '29', name: 'Metal', type: 'genre' },
    { id: '30', name: 'Heavy Metal', type: 'genre' },
    { id: '31', name: 'Black Metal', type: 'genre' },
    { id: '32', name: 'Funk', type: 'genre' },
    { id: '33', name: 'P-Funk', type: 'genre' },
    { id: '34', name: 'Funk Rock', type: 'genre' },
    { id: '35', name: 'Soul', type: 'genre' },
    { id: '36', name: 'Neo Soul', type: 'genre' },
    { id: '37', name: 'Motown', type: 'genre' },
    { id: '38', name: 'R&B', type: 'genre' },
    { id: '39', name: 'Contemporary R&B', type: 'genre' },
    { id: '40', name: 'Quiet Storm', type: 'genre' },
    { id: '41', name: 'Punk', type: 'genre' },
    { id: '42', name: 'Pop Punk', type: 'genre' },
    { id: '43', name: 'Hardcore Punk', type: 'genre' },
    { id: '44', name: 'Disco', type: 'genre' },
    { id: '45', name: 'Nu-Disco', type: 'genre' },
    { id: '46', name: 'Hi-NRG', type: 'genre' },
    { id: '47', name: 'Techno', type: 'genre' },
    { id: '48', name: 'Detroit Techno', type: 'genre' },
    { id: '49', name: 'Minimal Techno', type: 'genre' },
    { id: '50', name: 'House', type: 'genre' },
    { id: '51', name: 'Deep House', type: 'genre' },
    { id: '52', name: 'Progressive House', type: 'genre' },
    { id: '53', name: 'Trance', type: 'genre' },
    { id: '54', name: 'Psytrance', type: 'genre' },
    { id: '55', name: 'Uplifting Trance', type: 'genre' },
    { id: '56', name: 'Folk', type: 'genre' },
    { id: '57', name: 'Contemporary Folk', type: 'genre' },
    { id: '58', name: 'Traditional Folk', type: 'genre' },
    { id: '59', name: 'Latin', type: 'genre' },
    { id: '60', name: 'Salsa', type: 'genre' },
    { id: '61', name: 'Bachata', type: 'genre' },
    { id: '62', name: 'Reggaeton', type: 'genre' },
  ],
  mood: [
    { id: '1', name: 'Happy', type: 'mood' },
    { id: '2', name: 'Sad', type: 'mood' },
    { id: '3', name: 'Energetic', type: 'mood' },
    { id: '4', name: 'Calm', type: 'mood' },
    { id: '5', name: 'Romantic', type: 'mood' },
    { id: '6', name: 'Melancholic', type: 'mood' },
    { id: '7', name: 'Angry', type: 'mood' },
    { id: '8', name: 'Chill', type: 'mood' },
    { id: '9', name: 'Dreamy', type: 'mood' },
    { id: '10', name: 'Uplifting', type: 'mood' },
    { id: '11', name: 'Dark', type: 'mood' },
    { id: '12', name: 'Groovy', type: 'mood' },
    { id: '13', name: 'Mellow', type: 'mood' },
    { id: '14', name: 'Hopeful', type: 'mood' },
    { id: '15', name: 'Euphoric', type: 'mood' },
    { id: '16', name: 'Aggressive', type: 'mood' },
    { id: '17', name: 'Peaceful', type: 'mood' },
    { id: '18', name: 'Playful', type: 'mood' },
    { id: '19', name: 'Sentimental', type: 'mood' },
    { id: '20', name: 'Mysterious', type: 'mood' },
  ],
  custom: [],
};
